language: ruby
rvm:
  - 2.4.1

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master
  - testing

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

exclude: [vendor]

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
irc:
    channels:
      - "irc.chew.pro#soarn.pro"
      - "irc.chew.pro#anarchy"
    template:
      - "Build #%{build_number}: %{message} Time Elapsed: %{elapsed_time}. %{build_url}"
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
    skip_join: true
    nick: Jack bot an IRC-bot

  webhooks:
    urls:
      - https://n.tkte.ch/h/6117/EFSXXyMXFxkoBVnISc3ZD95A
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always

